# Generated by Django 3.0.3 on 2020-02-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="Nome"
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                ("full_text", models.TextField()),
                (
                    "dob",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Data de nascimento",
                    ),
                ),
                (
                    "missing_since",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Desaparecida(o) desde",
                    ),
                ),
                (
                    "eyes",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=16,
                        null=True,
                        verbose_name="Cor dos olhos",
                    ),
                ),
                (
                    "hair",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=16,
                        null=True,
                        verbose_name="Cor dos cabelos",
                    ),
                ),
                (
                    "skin",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=16,
                        null=True,
                        verbose_name="Cor da pele",
                    ),
                ),
                (
                    "mother",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Mãe"
                    ),
                ),
                (
                    "father",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Pai"
                    ),
                ),
                (
                    "last_seen_at",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Local onde foi vista(o) pela última vez",
                    ),
                ),
            ],
        ),
    ]
