# Generated by Django 3.0.3 on 2020-02-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kid", options={"ordering": ("name",), "verbose_name": "criança"},
        ),
    ]
