# Generated by Django 3.0.3 on 2020-02-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sort_kid_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kid",
            name="eyes",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Cor dos olhos",
            ),
        ),
        migrations.AlterField(
            model_name="kid",
            name="hair",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Cor dos cabelos",
            ),
        ),
        migrations.AlterField(
            model_name="kid",
            name="skin",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Cor da pele",
            ),
        ),
    ]
