# Generated by Django 3.0.5 on 2020-04-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_enlarge_color_text_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="kid",
            name="age_at_occurrence",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Idade quando desapareceu"
            ),
        ),
    ]
