# Generated by Django 3.0.5 on 2020-04-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_change_color_to_choice_field"),
    ]

    operations = [
        migrations.RemoveField(model_name="kid", name="last_seen_at",),
        migrations.AddField(
            model_name="kid",
            name="last_seen_at_city",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Cidade onde foi vista(o) pela última vez",
            ),
        ),
        migrations.AddField(
            model_name="kid",
            name="last_seen_at_state",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=2,
                null=True,
                verbose_name="UF onde foi vista(o) pela última vez",
            ),
        ),
    ]
