# Generated by Django 3.0.5 on 2020-04-27 00:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import web.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_adds_fields_for_city_and_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="KidImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to=web.core.models.get_file_name_in_storage,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif"]
                            )
                        ],
                    ),
                ),
                (
                    "kid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.Kid",
                        verbose_name="criança",
                    ),
                ),
            ],
            options={
                "verbose_name": "criança imagem",
                "verbose_name_plural": "criança imagens",
            },
        ),
    ]
